name: Go
on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Test
        #run: echo go test -v .
        run: echo go test  ./...  -count=1 -v
